-- ============================================================================
-- SUPABASE SCHEMA SETUP FOR SONG STREAK
-- ============================================================================
-- Run these SQL commands in your Supabase SQL Editor to set up the database

-- ============================================================================
-- 1. CREATE SONGS TABLE
-- ============================================================================
CREATE TABLE songs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Basic Song Information
  title TEXT NOT NULL,
  artist TEXT NOT NULL,
  instrument TEXT NOT NULL, -- 'Guitar', 'Bass', 'Drums', or 'Keys'

  -- Video & Media
  video_url TEXT NOT NULL,
  artwork_url TEXT,

  -- Theory Data
  key TEXT,
  tempo TEXT,
  time_signature TEXT,

  -- Practice Data
  difficulty TEXT,
  techniques TEXT[],

  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

  -- Indexes for performance
  CONSTRAINT valid_instrument CHECK (instrument IN ('Guitar', 'Bass', 'Drums', 'Keys')),
  CONSTRAINT valid_difficulty CHECK (difficulty IN ('Easy', 'Medium', 'Hard') OR difficulty IS NULL)
);

-- ============================================================================
-- 2. CREATE INDEXES
-- ============================================================================
CREATE INDEX idx_songs_user_id ON songs(user_id);
CREATE INDEX idx_songs_created_at ON songs(created_at);
CREATE INDEX idx_songs_instrument ON songs(instrument);
CREATE INDEX idx_songs_artist ON songs(artist);
CREATE INDEX idx_songs_title ON songs(title);

-- ============================================================================
-- 3. ENABLE ROW LEVEL SECURITY (RLS)
-- ============================================================================
ALTER TABLE songs ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- 4. CREATE RLS POLICIES
-- ============================================================================

-- Policy: Users can view their own songs
CREATE POLICY "Users can view their own songs"
  ON songs FOR SELECT
  USING (auth.uid() = user_id);

-- Policy: Users can insert their own songs
CREATE POLICY "Users can insert their own songs"
  ON songs FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Policy: Users can update their own songs
CREATE POLICY "Users can update their own songs"
  ON songs FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Policy: Users can delete their own songs
CREATE POLICY "Users can delete their own songs"
  ON songs FOR DELETE
  USING (auth.uid() = user_id);

-- ============================================================================
-- 5. CREATE UPDATED_AT TRIGGER
-- ============================================================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_songs_updated_at
  BEFORE UPDATE ON songs
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- NOTES
-- ============================================================================
-- 1. The songs table uses UUID for the primary key (generated by Supabase)
-- 2. user_id references auth.users(id) to link songs to authenticated users
-- 3. ON DELETE CASCADE ensures songs are deleted when a user is deleted
-- 4. RLS policies ensure users can only see/modify their own songs
-- 5. updated_at is automatically set to NOW() on update via trigger
-- 6. Indexes are created on commonly queried columns for performance
-- 7. CHECK constraints validate instrument and difficulty values
